### ISSUE TITLE
wrgl diff panic

### ISSUE THREAD

**Issue by dufferzafar** [wrgl/wrgl#5]
```
❯ wrgl diff
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/wrgl/wrgl/cmd/wrgl.runDiff(0x6, 0xc00035fc10, {0xe5eb48, 0xc000010040}, 0x70, {0xe66358, 0xc000010048}, {0x1614c80, 0x0, 0x0}, ...)
        /Users/runner/work/wrgl/wrgl/cmd/wrgl/diff_cmd.go:738 +0x58a
github.com/wrgl/wrgl/cmd/wrgl.newDiffCmd.func1(0xc0002cb900, {0x1614c80, 0x0, 0x0})
        /Users/runner/work/wrgl/wrgl/cmd/wrgl/diff_cmd.go:134 +0x573
github.com/spf13/cobra.(*Command).execute(0xc0002cb900, {0x1614c80, 0x0, 0x0})
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002cac80)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
        /Users/runner/work/wrgl/wrgl/wrgl/main.go:16 +0x55
```
        
The state is: I had committed a file, and then made a change to that file - but have not yet committed it. So I only have a single commit. I now want to view the current diff.

**Comment by pckhoi** [comment]
Sorry about that. It is a bug that `wrgl diff` would panic instead of showing a helpful message. You can use this incantation to diff against a file:
```bash
wrgl diff BRANCH_OR_COMMIT_HASH FILE_NAME --primary-key PRIMARY_KEY
```

**Comment by dufferzafar** [comment]
I guess this is fixed now.
